apiVersion: v1
kind: Namespace
metadata:
  name: frigatenfs
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigatepvc-data2
  namespace: frigatenfs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigatepvc-media2
  namespace: frigatenfs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"