apiVersion: v1
kind: Namespace
metadata:
  name: mediatx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediatx
  namespace: mediatx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediatx
  template:
    metadata:
      labels:
        app: mediatx
    spec:
      containers:
      - name: mediatx
        image: bluenviron/mediamtx
        ports:
        - containerPort: 8554
        - containerPort: 1935
          protocol: UDP
        - containerPort: 8189
          protocol: UDP
        env:
        - name: MTX_PROTOCOLS
          value: "tcp"
---
apiVersion: v1
kind: Service
metadata:
  name: mediatx-svc
  namespace: mediatx
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.240
spec:
  selector:
    app: mediatx
  ports:
    - protocol: TCP
      port: 8554
      name: rtsp
  type: LoadBalancer
